name: "Deploy Storybook to Github Pages"

on:
  push:
    branches:
      - main
    paths: ["stories/**", "src/components/**"]

jobs:
  ci:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy Storybook
        run: npm run deploy-storybook
